### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Aries007691** [zfbx/zdiscord#104]
**Describe the bug**
[zdiscord][2023-10-16 21:28:23][ERR]: Failed to fetch Discord server.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Information:**
 - FiveM Artifact #: [e.g. 3240]
 - Running QBCore?: [yes/no]
 - If running QBCore when did you last update it? [e.g. today, 1 week]
 - Have you checked for other issues reporting this bug?: [yes/no]

**Additional context**

**Comment by zfbx** [comment]
You're not giving me much to go on here.. There was a simple questionnaire and you just dropped a single line from the console.. How about some more details? Is this the first time you're running zdiscord? has this started happening randomly?
