### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by Nessa818** [zfbx/zdiscord#107]
Before submitting your question have you checked the check the [FAQ](https://github.com/zfbx/zdiscord/wiki) or checked for similar issues already?: [yes/no] yes i have

**Question:**
Describe your question..    how do i do this ```// STAFF CHAT
const EnableStaffChatForwarding = true;
const DiscordStaffChannelId = "1234198732841422966";
const AdditionalStaffChatRoleIds = [
    // "000000000000000",
];

// WHITELISTING / ALLOWLISTING
const EnableWhitelistChecking = false;
const DiscordWhitelistRoleIds = "000000000000000000, 000000000000000000";

// SLASH COMMANDS / DISCORD PERMISSIONS
const EnableDiscordSlashCommands = true;
const DiscordModRoleId = "1234198730790408211";
const DiscordAdminRoleId = "1234198730799059020";
const DiscordGodRoleId = "1234198730799059021";

// DISCORD BOT STATUS
const EnableBotStatusMessages = true;
const BotStatusMessages = [
    "{servername}",
    "{playercount} online",
];

// ACE PERMISSIONS
const EnableAutoAcePermissions = false;
const AutoAcePermissions = {
    // "example": "000000000000000000",
    // "example2": [ "000000000000000000", "000000000000000000"],
};

// Other
const SaveScreenshotsToServer = true;

/** ************************
 * WEBHOOK LOGGING SETTINGS
**************************/

const EnableLoggingWebhooks = false;
const LoggingWebhookName = "zLogs";
// put "&" in front of the id if you're to ping a role
const LoggingAlertPingId = "&000000000000000000";
// example: "bank": "https://discord.com/webhook/...",
const LoggingWebhooks = {
    "example": "",
};```

Information:
FiveM artifact #: [eg. 3200] artifact 8052
Using QBCore?: [yes/no]
When did you last update QBCore if you are using it?: [eg. yesterday, 1 week ago]yesterday

**Comment by Nessa818** [comment]
im using qbcore

**Comment by zfbx** [comment]
You're going to want to delete and recreate your webhook that you leaked, I deleted it from your message but anyone who's already seen it could do damage with it

Also I'm not quite sure what your question is
