### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by H4rdStyl3** [zfbx/zdiscord#11]
Hey after some time i got an error in my console, i use my own server Windows Server 2016, Gamebuild 2189 with onesync infinity.
The Bot start correct also all commands working fine.

[     script:zdiscord] Logged in on Discord as HSH Bot!
[      script:qb-core] [qb-core:LOG] PsYch0StylZ PLAYER SAVED!
[      script:qb-core] [qb-core:LOG] PsYch0StylZ PLAYER SAVED!
[     script:zdiscord] Error: Error: Connection reset by peer
[     script:zdiscord]     at Shard._onWSClose (C:\txData\QBCoreFramework_3DD161.base\resources\[standalone]\zdiscord\libs\eris\lib\gateway\Shard.js:2137:23)
[     script:zdiscord]     at WebSocket.emit (events.js:210:5)
[     script:zdiscord]     at WebSocket.emitClose (C:\txData\QBCoreFramework_3DD161.base\resources\[standalone]\zdiscord\libs\ws\lib\websocket.js:247:10)
[     script:zdiscord]     at TLSSocket.socketOnClose (C:\txData\QBCoreFramework_3DD161.base\resources\[standalone]\zdiscord\libs\ws\lib\websocket.js:1102:15)
[     script:zdiscord]     at TLSSocket.emit (events.js:215:7)
[     script:zdiscord]     at net.js:658:12
[     script:zdiscord]     at TCP.done (_tls_wrap.js:481:7)
[     script:zdiscord] Logged in on Discord as HSH Bot!

**Comment by zfbx** [comment]
This seems to be related to eris and discord and connections to the API, usually just means the connection was dropped by discord but it recovers without issue. I'll be porting to use discord.js soon depending on stability with cfx's new node.js changes

**Comment by H4rdStyl3** [comment]
Ty for your feedback was a bit confused since it spams the console :D
