### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Ortors** [zfbx/zdiscord#110]
**Question:**
What can i do?
![image](https://github.com/zfbx/zdiscord/assets/171589132/233e59b7-c201-4fbe-8b85-cd238409dbe4)

Information:
FiveM artifact #: [8633]
Using QBCore?: [no]

**Comment by zfbx** [comment]
It .. tells you right there in the warning exactly what you can do.. go to https://discord.com/developers/applications/ , click on your bot, go to Bot and enable the intents like so:

![image](https://github.com/zfbx/zdiscord/assets/1414927/735b7441-d3b0-4746-a91a-2c49cd0a6fc2)
