### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mas7or123** [zfbx/zdiscord#2]
i get this error when i start the script
![image](https://user-images.githubusercontent.com/63555033/128631043-a30ebf46-c609-4029-8a07-7aef4b55b71d.png)

**Comment by zfbx** [comment]
https://github.com/zfbx/zdiscord/wiki/FAQ#console-is-giving-an-error-of-disallowed-intent-specified

**Comment by ItzDabbzz** [comment]
Maybe just ready 👀
