### ISSUE TITLE
multiple role id

### ISSUE THREAD

**Issue by y0p4** [zfbx/zdiscord#21]
Before submitting your question have you checked the check the [FAQ](https://github.com/zfbx/zdiscord/wiki) or checked for similar issues already?: yes

**Question:**
Hey, when I need to put multiple DiscordModRoleId how I can do it?

Information:
FiveM artifact #: 4821
Using QBCore?: yes
When did you last update QBCore if you are using it?: last update

**Comment by zfbx** [comment]
It only supports 1 mod role, 1 admin role and 1 god role currently from the config but you can manually add more roles to be mod tier.
In server.js at the end is a function called loadDiscordPermissions, modify it to look more like:
```js
function loadDiscordPermissions() {
    const mod = { id: config.modRole, type: 1, permission: true };
    const mod2 = { id: "MOD-ROLE-ID2", type: 1, permission: true }; // Added
    const mod3 = { id: "MOD-ROLE-ID3", type: 1, permission: true }; // Added
    const admin = { id: config.adminRole, type: 1, permission: true };
    const god = { id: config.godRole, type: 1, permission: true };
    const own = { id: "142831624868855808", type: 2, permission: true };
    config.perms = {
        "mod": [ mod, mod2, mod3, admin, god, own ], // Changed
        "admin": [ admin, god, own ],
        "god": [ god, own ],
    };
}
```

**Comment by y0p4** [comment]
ok thank you
