### ISSUE TITLE
[BUG] DELAY PLAYER ONLINE 

### ISSUE THREAD

**Issue by xenfovn** [zfbx/zdiscord#22]
CURRENT PLAYER NUMBER INSIDE BOT NAME FREQUENTLY DELAY OR UPDATE SLOWLY  
![image](https://user-images.githubusercontent.com/55439243/138572726-d6f7d199-0eac-4c81-bc30-ee40adfb1103.png)
BUT MY SERVER 5 PLAYERS

**Comment by zfbx** [comment]
For starters, why are you yelling? x_x
Second, there's missing information in your ticket, I put a lot of work into those templates D;

and to answer your question, the status message updates every 30 seconds, if you'd like it to update more frequently change the `30000` in `/events/ready.js` at the bottom to something lower like 10 seconds ( 10000 ) *It's in milliseconds btw (1sec = 1000ms)
