### ISSUE TITLE
[Feature] check item inventory and vehicles

### ISSUE THREAD

**Issue by xenfovn** [zfbx/zdiscord#27]
i think it would be great if we could have a command that can check the player's item or vehicle owned through citizenid

and add vehicles to players

**Comment by zfbx** [comment]
Would be nice to have something like this

**Comment by zfbx** [comment]
I don't plan on implementing this but if you want to submit a PR I'll surely take a look. currently I'm happy with the state of the resource. for now I'm going to close this issue
