### ISSUE TITLE
Even though Fivem artifacts version is 4394, it gives an error and the error is:

### ISSUE THREAD

**Issue by DansValley** [zfbx/zdiscord#28]
Before submitting your question have you checked the check the [FAQ](https://github.com/zfbx/zdiscord/wiki) or checked for similar issues already?: [yes/no]

**Question:**

Even though Fivem artifacts version is 4394, it gives an error and the error is:
https://prnt.sc/1z4zypy

Information:
FiveM artifact #: [eg. 4394]
Using QBCore?: YES
When did you last update QBCore if you are using it?: [eg.  8 months ago]

**Comment by ItzDabbzz** [comment]
Try updating your artifact version to the latest one.

**Comment by DansValley** [comment]
FiveM artifact #: [eg. 4394] 

up to date already

Is there a version you recommend?

**Comment by ItzDabbzz** [comment]
4960 was the latest artifact update not 4394? From the views of it you aren't updated as '/server:4800' is Node16+

**Comment by DansValley** [comment]
https://prnt.sc/1z5lrkw

/server:4394

should i change it to ?

**Comment by ItzDabbzz** [comment]
If you mean change the fxmanifest.lua line no, you should not change that. Simple just update your server artifacts like the in the picture you sent me.

**Comment by DansValley** [comment]
Hi I get this error


https://prnt.sc/1z5odyn

help me please

**Comment by DansValley** [comment]
https://prnt.sc/1z5p6xy

**Comment by zfbx** [comment]
> Hi I get this error
> 
> https://prnt.sc/1z5odyn
> 
> help me please

You need to follow the setup guide to prevent that

for the last error just delete the package-lock.json file in the resource which shouldn't be there unless you tried to `npm install`

**Comment by zfbx** [comment]
I'm gonna assume you solved the problem, if not reopen or join the discord in the readme
