### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Manliketjb** [zfbx/zdiscord#29]
Before submitting your question have you checked the check the [FAQ](https://github.com/zfbx/zdiscord/wiki) or checked for similar issues already?: [yes/no]

**Question:**
Does "DeprecationWarning: Buffer() is deprecated due to security and usability issues" mean anything important?

**Comment by zfbx** [comment]
https://zfbx.github.io/zdiscord/faq#buffer-deprecation-warning
