### ISSUE TITLE
revive error

### ISSUE THREAD

**Issue by mas7or123** [zfbx/zdiscord#3]
![image](https://user-images.githubusercontent.com/63555033/129180213-efbbf89c-88e2-47da-82f9-bacbf70e293b.png)
i get this error when i try to revive someone

**Comment by zfbx** [comment]
@mas7or123 what version of qbcore are you running?

**Comment by zfbx** [comment]
if you're not using https://github.com/qbcore-framework (The only official version of QB) I can't support your problem. and there haven't been any reports of problems from anyone in the qbcore community with that functionality or changes related

**Comment by mas7or123** [comment]
I have know why i become the error im dum i have stated the zdiscord before the qb-core
