### ISSUE TITLE
[BUG] discord.js is not being found

### ISSUE THREAD

**Issue by MattiVboiii** [zfbx/zdiscord#37]
**Describe the bug**

Whenever I start the script, next error appears

![image](https://user-images.githubusercontent.com/57048210/145807890-609af9ca-b121-4a14-aa8e-8b8eea3cf44b.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/57048210/145807955-17b4712b-381f-49a3-b70c-626565a9c92f.png)

**Information:**
 - FiveM Artifact #: Latest recommended (4394)
 - Running QBCore?: [yes]: it is renamed but still should work with QBCore
 - If running QBCore when did you last update it? [custom, so not]
 - Have you checked for other issues reporting this bug?: [yes]

**Additional context**

**Comment by zfbx** [comment]
so you don't actually want to use fivem's latest recommended as it's VERY out of date and doesn't support the version of node zdiscord is built off of you want to use a version that's 4890 or [higher (5077)](https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/5077-808987adcfc684684621e732e7959c96d9872842/server.7z)

**Comment by MattiVboiii** [comment]
still getting the same error mate, "cannot find discord.js"

**Comment by zfbx** [comment]
do you have yarn installed? here's my version that works confirmed https://cdn.discordapp.com/attachments/862934532110024734/918724690363691038/yarn.zip and do you have any other errors in your console further up that say anything about like a failed build or missing dependencies?

**Comment by MattiVboiii** [comment]
just used your yarn, now I get this error xD
![image](https://user-images.githubusercontent.com/57048210/145815315-0ea09d60-b9a4-4aa7-a18e-c389f4f8a978.png)

**Comment by zfbx** [comment]
that is certainly a new error for me.. here's what I'd suggest:

first just try restarting the server and see if it works the second time.

If that doesn't work try to clear the server cache and run again, the old yarn remnants might be in there causing trouble. 

If neither of those work, let me know and I'll have a few other ideas that are more experimental

**Comment by MattiVboiii** [comment]
I deleted the yarn-cache folder, didn't do much, same error, now im clearing out the whole server cache

**Comment by MattiVboiii** [comment]
nope, still crashed
![image](https://user-images.githubusercontent.com/57048210/145818649-d4409d82-1eb6-46c0-90d0-ee9437a92f8b.png)

**Comment by zfbx** [comment]
okay so let's try this instead. 
## First the easy way:
download and extract this files into the zdiscord directory [zdiscord_modules.zip](https://github.com/zfbx/zdiscord/files/7704093/zdiscord_modules.zip)
and start the server.
## The harder way:
if you don't already have it, install [node.js](https://nodejs.org) (*I recommend 16.13.1 LTS)
open up the zdiscord folder and type `cmd` into the top bar (not the search bar)
In the command prompt that comes up type `npm i` and it will install everything you need into that folder.
add a file called `.yarn.installed` (with the dot at the start) in that same directory and run the server, it should skip over yarn completely at that point.

**Comment by MattiVboiii** [comment]
IT WORKS!

Tysm for your support and patience, you are the best! Script works great on my discord :)

**Comment by zfbx** [comment]
Glad to hear :) Enjoy, sorry it caused so much of a headache there at the start, hopefully one day fivem will move away from yarn in favor of something better xD or at least update it where it's more stable
