### ISSUE TITLE
QBCore slash commands are not showing up in Discord

### ISSUE THREAD

**Issue by alexanderbodnar** [zfbx/zdiscord#38]
Before submitting your question have you checked the check the [FAQ](https://github.com/zfbx/zdiscord/wiki) or checked for similar issues already?: yes

**Question:**
After setting up the script. Everything works except the QBCore scripts. They wont even show up in discord text chat when typing /. Normal ones appear + /kill but commands like /money /revive are not working

Information:
FiveM artifact #: [eg. 3200]
Using QBCore?: yes
When did you last update QBCore if you are using it?: using old version, last updated 3 months ago

**Comment by zfbx** [comment]
If your version is before switch to the export you'll want to follow this guide https://zfbx.github.io/zdiscord/faq#qbcore-commands-arent-loading under "QBCore commands aren’t loading" If you've modified anything of qbcore like the name or anything like that you'll have to update those accordingly
