### ISSUE TITLE
[BUG] Error: write EIO

### ISSUE THREAD

**Issue by xenfovn** [zfbx/zdiscord#40]
![image](https://user-images.githubusercontent.com/55439243/148855629-81fc3685-1196-4c90-9941-f5330664363d.png)
i need help fix it

**Comment by zfbx** [comment]
There's a template that askes you questions that could help me help you better when you create an issue.. use it or I wont bother helping. I need more information about your setup

**Comment by xenfovn** [comment]
> There's a template that askes you questions that could help me help you better when you create an issue.. use it or I wont bother helping. I need more information about your setup

it working normal in vps linux and localhost windows , but i using vps windows 2012 it error

**Comment by xenfovn** [comment]
fixed it , just kick and invite bot again
