### ISSUE TITLE
[Feature] Persistent player count channel

### ISSUE THREAD

**Issue by napei** [zfbx/zdiscord#42]
Would be nice to have a persistent locked voice channel in the server, that updates every second or so with the online player count. A lot of other bots do this with discord member counts. Potentially this could also be dynamic like the status messages.

Format could be: `Players Online: {playercount}`

Example:
![image](https://user-images.githubusercontent.com/8946502/149604623-4f90c7d9-9cb3-404c-8f89-7e85e3ffacbf.png)

**Comment by zfbx** [comment]
That's actually extremely easy to do with an addon module, I'll throw one together real quick as an example

**Comment by zfbx** [comment]
https://github.com/zfbx/zdiscord/commit/3f3c11ca2d7bbf854d7db1bc0ffbe2f348a5d18e there you go, just drop that in your server/addons folder with the channel id you want updated and it'll do exactly like you suggested

**Comment by napei** [comment]
> [3f3c11c](https://github.com/zfbx/zdiscord/commit/3f3c11ca2d7bbf854d7db1bc0ffbe2f348a5d18e) there you go, just drop that in your server/addons folder with the channel id you want updated and it'll do exactly like you suggested

That's awesome, thank you for that. Is `zdiscord:ready` not implemented or do I need to raise that myself. I can't find any other references to it (not working as that event isn't called).

**Comment by zfbx** [comment]
that was added in this commit https://github.com/zfbx/zdiscord/commit/f47074d8d9cccffbe67a9cc038b038aae5c47462

**Comment by napei** [comment]
Ah I see. Not in the latest release.

Is it in a safe state to use `djs` instead of a release?

**Comment by zfbx** [comment]
Ohh yes sorry, I haven't built a release in a little bit, yes the main branch is always stable. I'll get a release built also

**Comment by napei** [comment]
Awesome. Thanks :)

**Comment by napei** [comment]
Thanks for that. All working now 😄 https://github.com/zfbx/zdiscord/releases/tag/v7.1.0

**Comment by napei** [comment]
@zfbx just a PSA, apparently there is a very strong rate limit on channel name changes.

https://discord.com/channels/613425648685547541/697138785317814292/715995470048264233

![image](https://user-images.githubusercontent.com/8946502/149609606-b977a491-4b0d-4f54-b9dd-10898fc07757.png)

**Comment by zfbx** [comment]
Oh damn.. well figured they'd do that eventually.. that's brutal though 10 whole minutes.. used to be way less, guess people abused it too much :( that's unfortunate. if desired could do the same with editing a message in a channel

**Comment by zfbx** [comment]
Pushed a hotfix and updated the release download so other's don't run into that, thank you very much for pointing that out ❤️
