### ISSUE TITLE
Need some info

### ISSUE THREAD

**Issue by MarioRogue** [zfbx/zdiscord#43]
I am trying to figure out what discord.js version is running with the bot can't find it nowhere,
when I am trying to get the event "guildMemberUpdate" oldMember and newMember are just undefined, and I can't figure something out

**Comment by ItzDabbzz** [comment]
Can i please see your guildMemberUpdate event?

**Comment by zfbx** [comment]
discord.js version 13.6.0

Made guildMemberUpdate.js in server/events with
```js
module.exports = {
    // https://discord.js.org/#/docs/discord.js/stable/class/Client?scrollTo=e-guildMemberUpdate
    name: "guildMemberUpdate",
    run: async (client, oldMember, newMember) => {
        if (newMember.user.bot) return;
        if (oldMember.nickname !== newMember.nickname) {
            console.log(`Nickname changed to ${newMember.nickname}`);
        }
    },
};
```
and it worked just fine
![cmd_jfDfcRe3LR](https://user-images.githubusercontent.com/1414927/149640059-2676316c-07a0-4e99-b58a-9c3dd0a7159c.png)

**Comment by MarioRogue** [comment]
> discord.js version 13.6.0
> 
> Made guildMemberUpdate.js in server/events with
> 
> ```js
> module.exports = {
>     // https://discord.js.org/#/docs/discord.js/stable/class/Client?scrollTo=e-guildMemberUpdate
>     name: "guildMemberUpdate",
>     run: async (client, oldMember, newMember) => {
>         if (newMember.user.bot) return;
>         if (oldMember.nickname !== newMember.nickname) {
>             console.log(`Nickname changed to ${newMember.nickname}`);
>         }
>     },
> };
> ```
> 
> and it worked just fine ![cmd_jfDfcRe3LR](https://user-images.githubusercontent.com/1414927/149640059-2676316c-07a0-4e99-b58a-9c3dd0a7159c.png)

I think not having the client prop might of fucked with everything, it works properly.
Thank you for your answer,
