### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by INDOmonyet** [zfbx/zdiscord#46]
Hi,

Im just running qbus this week, bud i had a qeustion it will says he cannot found the module.

<img>https://imgshare.io/images/2022/01/28/wda.png</img>

**Comment by zfbx** [comment]
first try to restart the bot `ensure zdiscord` and see if it throws an error before that.

That usually means that yarn wasn't installed or didn't install the required node_modules properly. if you have a `yarn.installed` file delete it. if you have node_modules folder delete it and restart the script.

If yarn is the issue try this version <https://cdn.discordapp.com/attachments/862934532110024734/918724690363691038/yarn.zip>

**Comment by INDOmonyet** [comment]
Oke thanks for the quick response,
Thats working fine, but now he wil say that my bot is not right

 x
[zdiscord][2022-1-28 01:14:42][ERR]: NO COMMAND CREATION PERMISSIONS - You must reinvite the bot to your server with the invite link provided in setup

[     script:zdiscord] SCRIPT ERROR in promise (unhandled): TypeError: Cannot read properties of undefined (reading 'reduce')

[     script:zdiscord] > <unknown> (C:\Users\Administrator\Desktop\Leeuwarden_Framework\server-data\resources\zdiscord\server\events\ready.js:20)

[     script:zdiscord] > processTicksAndRejections (node:internal/process/task_queues:96)

[     script:zdiscord] > async Object.run (C:\Users\Administrator\Desktop\Leeuwarden_Framework\server-data\resources\zdiscord\server\events\ready.js:19)

[     script:zdiscord]


The bot got the 2 intents

***@***.***


…
***@***.***

The discordguildid = my own server id right?

Thank you for your time,

greatsz

**Comment by zfbx** [comment]
That first error there tells you exactly what is wrong. in the setup steps it tells you to use a specific type of invite link to invite your bot into your server with the permission to create slash commands:

> 3. Add the bot to your server - To do this copy the following link and replace `YOUR-BOT-ID` with your bots ID then follow the invite process to your discord from the link
`https://discord.com/api/oauth2/authorize?client_id=YOUR-BOT-ID&permissions=8&scope=bot%20applications.commands`<br>
**NOTE: If the bot is already in your server you might need to run the link above again anyways to make sure it can get the needed slash command scope (unrelated to permissions)**

**Comment by zfbx** [comment]
oh and yes the discordguildid is your own server id

**Comment by INDOmonyet** [comment]
Thank u, i need to read better haha.

It works fine now 😊
Only the /revive looks like it doesnt work bud maby im doing wrong 😉

thanks

**Comment by zfbx** [comment]
Are you using official [qbcore](https://github.com/qbcore-framework) or actually using an old "qbus"? and if using qbcore, when was it last updated?

**Comment by INDOmonyet** [comment]
QBcore

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________
