### ISSUE TITLE
Having a problem running the bot

### ISSUE THREAD

**Issue by nitayStain** [zfbx/zdiscord#49]
Hey! while running the bot i noticed a problem. after about a couple of minutes, the bot would shut down.
any solutions?

**Comment by zfbx** [comment]
Are you loading a bunch of maps and vehicles? if so are you loading them before or after the bot? if after they have a chance of hanging the bot's handshake event with the discord api and will cause it to disconnect requiring it to be restarted manually. the fix if that's the case is to ensure all your maps, vehicles and clothing BEFORE all your scripts

**Comment by zfbx** [comment]
Any updates?

**Comment by zfbx** [comment]
gonna assume this has been resolved
