### ISSUE TITLE
Error: Error: Connection reset by peer

### ISSUE THREAD

**Issue by ItsAegeus** [zfbx/zdiscord#5]
![image](https://user-images.githubusercontent.com/42155010/131724220-0de268ad-a49a-4399-a8bc-5cd36980e907.png)
Been having this error now out of blue nothing has changed.
Worked fine for 24hrs then that.

**Comment by ItsAegeus** [comment]
I was a dumb ass... WHOOPS.

**Comment by scarecrow313** [comment]
> I was a dumb ass... WHOOPS.

I guess I am too lol. What happened for you? First time Im seeing it today and its been running fine before.

**Comment by ItsAegeus** [comment]
> > I was a dumb ass... WHOOPS.
> 
> I guess I am too lol. What happened for you? First time Im seeing it today and its been running fine before.

Im getting the error again. I switched Dedis and thought maybe it was cause of the build. Did a clean install went 6hrs now and one just showed up.

**Comment by scarecrow313** [comment]
Yea I didn't have any issue until today so funny we are both seeing it. Otherwise it works great. Currently its saying that and than keeps logging back into discord. lol

**Comment by zfbx** [comment]
It's because of discord's API, it happens anytime the connection is lost or dropped but it does recover itself as soon as it gets a ping again from discord
