### ISSUE TITLE
[BUG] /players gives error

### ISSUE THREAD

**Issue by MattiVboiii** [zfbx/zdiscord#50]
**Describe the bug**
Whenever I do /players in the Discord, it loads forever and gives the following error in the console..

**To Reproduce**
1. Go to 'Discord'
2. Type '/players'
3. See error in console

**Expected behavior**
Giving a list of players in the server.

**Screenshots**
![image](https://user-images.githubusercontent.com/57048210/157275166-5828cb27-4012-4590-8395-ba2e301d8acc.png)

**Information:**
 - FiveM Artifact #: tuner DLC
 - Running QBCore?: [yes]
 - If running QBCore when did you last update it? [1 month ago I think?]
 - Have you checked for other issues reporting this bug?: [yes]

Thankyou for the following help! :)

**Comment by zfbx** [comment]
Did you have a previous version of zdiscord and update to the more recent version afterwards? if so you'll want to delete `node_modules` and `yarn.installed` and it should fix it, cause it was a change to the discord.js framwork. 

Alternatively you can go into `/server/bot.js` and replace 3 lines:
line 102 to
```js
embeds: [pages[page].setFooter(`Page ${page + 1} / ${pages.length}`)],
```
line 119 to
```js
await i.editReply({ embeds: [pages[page].setFooter(`Page ${page + 1} / ${pages.length}`)], components: [row] });
```
and line 125 to
```js
curPage.edit({ embeds: [pages[page].setFooter(`Page ${page + 1} / ${pages.length}`)], components: [disabledRow] });
```

Let me know which action you take and if either fails :)

**Comment by zfbx** [comment]
Any update on this?

**Comment by zfbx** [comment]
gonna assume this has been resolved
