### ISSUE TITLE
Having a problem running the bot [BUG]

### ISSUE THREAD

**Issue by MYONES-69** [zfbx/zdiscord#51]
![Screenshot 2022-03-09 001528](https://user-images.githubusercontent.com/93837957/157326410-92b17fdc-0f68-476a-ac53-0224b91b710f.png)

**Comment by zfbx** [comment]
Yeah... I think that error should be pretty self explanatory there..

**Comment by MYONES-69** [comment]
I did not understand you exactly what the problem is, please if you could explain the error?!

**Comment by zfbx** [comment]
Right in the error there it tells you that the bot wasn't invited to your discord server properly and to invite it again using the proper link provided in the setup guide:

> **3.** Add the bot to your server - To do this copy the following link and replace YOUR-BOT-ID with your bots ID then follow the invite process to your discord from the link `https://discord.com/api/oauth2/authorize?client_id=YOUR-BOT-ID&permissions=8&scope=bot%20applications.commands`
**NOTE: If the bot is already in your server you might need to run the link above again anyways to make sure it can get the needed slash command scope (unrelated to permissions)**

The important bit being that the invite url has `&scope=bot%20applications.commands` on the end
