### ISSUE TITLE
Discord commands not working

### ISSUE THREAD

**Issue by justBMR** [zfbx/zdiscord#53]
Good night. I performed all the steps and I can already use the role-based whitelist. The problem is that I can't send command through discord. Whenever I type a / , all commands appear unavailable and even if I try to execute them, nothing happens.

Does anyone know a way to solve the problem

**Comment by chrislenga** [comment]
Sounds to me like you didn't follow the steps in the beginning when inviting the bot to your Discord.

**Comment by zfbx** [comment]
If you can see the commands the bot was invited correctly but you don't have the permissions to use them which means you don't have one of the roles configured for mod, admin or god

**Comment by chrislenga** [comment]
If that doesn't work, definitely look over the issue at the start with the inviting. We had two issues with this where we could see the slash commands, but couldn't use them, and the bot required a reinvite into the server. One in fact recently with our ticket bot where every command was visible, but couldn't be interacted with, but as soon as we kicked it, reinvited with app commands, it worked like a charm.

**Comment by justBMR** [comment]
Thank you for your help. The problem was that I didn't copy the correct role ids. It is now working properly. Thank you one more time. hug

**Comment by zfbx** [comment]
Glad it's working :) those ids can throw people sometimes
