### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by milotiro95** [zfbx/zdiscord#55]
**Describe the bug**
(node:15524) DeprecationWarning: Message#deleted is deprecated, see https://github.com/discordjs/discord.js/issues/7091.
(Use `FXServer --trace-deprecation ...` to show where the warning was created)
> FXServer --trace-deprecation

That's what i have on my server running zdiscord. I don't know discord.js i see it is on my zdiscord folder.

**To Reproduce**
Just drag en drop into a server running directly and the fxserver will show a warning 

Do you have an idea how to fix ? I'm using Artifact 5151

New Error on 5300 : (node:9264) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `FXServer --trace-deprecation ...` to show where the warning was created)

**Comment by zfbx** [comment]
yeah, it's been deprecated in the current version of discord.js (the framework zdiscord is build off of) it still works fine currently. I believe it's probably being triggered from the pagninator (used for commands like /players) for when there could be more than 4000 character replies which would break a message being sent. If you want to get rid of it.. replace these 4 lines <https://github.com/zfbx/zdiscord/blob/b2a32ad5871d5bb15d35f64e5f00a9de9451c7a3/server/bot.js#L123-L126> with these 2
```js
const disabledRow = new MessageActionRow().addComponents(buttonList[0].setDisabled(true), buttonList[1].setDisabled(true));
curPage.edit({ embeds: [pages[page].setFooter({ text: `Page ${page + 1} / ${pages.length}` })], components: [disabledRow] }).catch(console.error);
```

**Comment by milotiro95** [comment]
Thank you for the feedback that was fast ! Yes I hate error so It will be perfect if that work. I just push the edit and will let you know if all is good by the end of the night :).

**Comment by milotiro95** [comment]
Work like a charm thank you a lot for the support :)

**Comment by zfbx** [comment]
Glad to hear :) I'll go ahead and throw this on the main repo for others
