### ISSUE TITLE
Couldn't find the binary git

### ISSUE THREAD

**Issue by bedar89** [zfbx/zdiscord#6]
Whenever I try to run zdiscord, the log tells me the following:

```
yarn install v1.22.5
info No lockfile found.
[1/4] Resolving packages...
error Couldn't find the binary git
[ citizen-server-impl] Building resource zdiscord failed.
[ citizen-server-impl] Error data: yarn failed!
```

I'm running the henkallsn/fivem_esx_bundle:light docker container and everything updated to latest version.

**Comment by zfbx** [comment]
Seems you're missing `git` which yarn uses to pull the resources. probably something along these lines `RUN apt-get -y install git`. I will see about making a version of the project that doesn't depend on yarn if I can but it depends on if there's platform specific builds of anything

**Comment by Boom1053** [comment]
Having same issue. i have yarn running from what i see in txAdmin

**Comment by zfbx** [comment]
I'm almost done reworking it without the yarn dependency which should prevent any of these common issues with git and yarn. should be done before the end of the day

**Comment by zfbx** [comment]
Last commits fix this error. Have fun :)

**Comment by zfbx** [comment]
If anyone else finds this again in the future copy the files from this zip into your zdiscord directory https://cdn.discordapp.com/attachments/862934532110024734/967320705609904148/zdiscord_modules.zip
