### ISSUE TITLE
/revive

### ISSUE THREAD

**Issue by MittelGrabung62** [zfbx/zdiscord#62]
I really enjoying your bot! Huge Thanks.
But may add a revive function then your bot would be perfect.

**Comment by milotiro95** [comment]
Already exist lol /revive

**Comment by zfbx** [comment]
there's a revive https://github.com/zfbx/zdiscord/blob/djs/server/commands/qb-revive.js and revive all https://github.com/zfbx/zdiscord/blob/djs/server/commands/qb-reviveall.js for qbcore but if you're using esx or something you'll have to probably modify them slightly and remove `qb-` from the file name as any command with `qb-` only loads if qbcore is detected

**Comment by MittelGrabung62** [comment]
I´ll try. Thanks
