### ISSUE TITLE
Qbcore commands not working

### ISSUE THREAD

**Issue by Vuxifiedd** [zfbx/zdiscord#63]
**Question:**

Information:
Certain commands work like, screenshot player, restart resources. but certain commands like revive a player, or setjob is not working why?
Using QBCore?: [yes
When did you last update QBCore if you are using it? A month ago

**Comment by zfbx** [comment]
Where did you get your version of QBCore? was it from https://github.com/qbcore-framework ?

**Comment by Vuxifiedd** [comment]
Yes
