### ISSUE TITLE
[BUG] [ERR]: NO COMMAND CREATION PERMISSIONS

### ISSUE THREAD

**Issue by Tylerscott902** [zfbx/zdiscord#65]
Have added the "add_ace resource.zdiscord command allow" to server CFG, and reinvited the bot to my discord multiple times, but I continue to get this error in my console:

"[zdiscord][2022-6-14 16:10:06][ERR]: NO COMMAND CREATION PERMISSIONS - You must reinvite the bot to your server with the invite link provided in setup"

**Comment by zfbx** [comment]
reinvited the bot to your discord server with this invite `https://discord.com/api/oauth2/authorize?client_id=YOUR-BOT-ID&permissions=8&scope=bot%20applications.commands` ?.. specifically ending in **applications.commands** cause this invite will fix that as stated in the error. you can't use just any bot invite link

**Comment by Tylerscott902** [comment]
Thank you. Apparently, I'm a dingus... Sorry for the stupid bug report xD
