### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by djraymond** [zfbx/zdiscord#69]
![image](https://user-images.githubusercontent.com/80656581/177768023-a9c0622a-b3f9-4e31-8688-7bec60848b56.png)

![image](https://user-images.githubusercontent.com/80656581/177768074-62c6845d-39e4-4f6f-9280-c86380c01b20.png)

**Comment by adtgamer** [comment]
help

**Comment by zfbx** [comment]
enable all 3 and make sure you're using the same token @adtgamer
