### ISSUE TITLE
errors in console 

### ISSUE THREAD

**Issue by RustinCassiem** [zfbx/zdiscord#7]
I setup the bot with documentation provided and getting this error 

[     script:zdiscord] Error: Error: Disallowed intents specified
[     script:zdiscord]     at Shard._onWSClose (/home/container/txData/staging_v2.base/resources/[Scripts]/zdiscord/node_modules/eris/lib/gateway/Shard.js:2133:23)
[     script:zdiscord]     at WebSocket.emit (events.js:210:5)
[     script:zdiscord]     at WebSocket.emitClose (/home/container/txData/staging_v2.base/resources/[Scripts]/zdiscord/node_modules/ws/lib/websocket.js:246:10)
[     script:zdiscord]     at TLSSocket.socketOnClose (/home/container/txData/staging_v2.base/resources/[Scripts]/zdiscord/node_modules/ws/lib/websocket.js:1063:15)
[     script:zdiscord]     at TLSSocket.emit (events.js:215:7)
[     script:zdiscord]     at net.js:658:12
[     script:zdiscord]     at TCP.done (_tls_wrap.js:481:7)

**Comment by zfbx** [comment]
https://github.com/zfbx/zdiscord/wiki/FAQ#console-is-giving-an-error-of-disallowed-intent-specified

**Comment by RustinCassiem** [comment]
thank you
sorted

**Comment by RustinCassiem** [comment]
dump question, can the setjob from qb be implemented for esx?

**Comment by GhzGarage** [comment]
ESX is not supported

**Comment by RustinCassiem** [comment]
thanks

**Comment by zfbx** [comment]
> dumb question, can the setjob from qb be implemented for esx?

So this is a bit embarrassing, I'm actually dropping the esx support (It technically was never fully implemented or tested) I don't actually have any esx servers to test and the person who said they'd add it never did so, I'm sorry. but if you don't update to the next version the code is there ready to customize
