### ISSUE TITLE
[Feature] Connect queue

### ISSUE THREAD

**Issue by TonybynMp4** [zfbx/zdiscord#71]
My very (un)original idea is to add a connect queue (or using a pre existing one like the one qbcore uses for example) and adding the possibility to give queue priority through discord roles.

**Comment by zfbx** [comment]
If you want to try and take this on, I've heard some people have had success, but it might need work, I never officially finished it https://github.com/zfbx/zqueue

**Comment by TonybynMp4** [comment]
😞
