### ISSUE TITLE
You don't have permission to use this command

### ISSUE THREAD

**Issue by KazukiDev** [zfbx/zdiscord#72]
i did all the steps right and when i go to discord and do /whitelist  it says You don't have permission to use this command how do i fix that

**Comment by zfbx** [comment]
You have the discord role set in the config as the "god" role? as that's a god level command?

**Comment by KazukiDev** [comment]
how do i set that up

**Comment by zfbx** [comment]
you just said you did all the steps right? step 7 was to `adjust the config` more info: https://zfbx.github.io/zdiscord/config

**Comment by KazukiDev** [comment]
i did

**Comment by KazukiDev** [comment]
In the config i dont see where to set the god permistion

**Comment by zfbx** [comment]
https://github.com/zfbx/zdiscord/blob/bc564a0602ffa4c389103a5bfb1f4bcb65dae8da/config.js#L47

**Comment by KazukiDev** [comment]
Ok i fix it thank you
