### ISSUE TITLE
Car spawn

### ISSUE THREAD

**Issue by GearXgaMer** [zfbx/zdiscord#74]
Hello
Is it possible to modify /vehicle give command that the car will spawn next to player and not in garage

**Comment by zfbx** [comment]
Yes and no? It's not really a simple process to do at all and a lot of variables make it weird. for example if the server is a RP server then  a car just appears next to them randomly wherever they are? pretty unrealistic. and if someone is in the middle of doing something somewhere a car shouldn't be like in an MLO or something and someone runs the command there's not a car stuck in an MLO which requires someone to deal with. then there's all the code on top of it to make it spawn near them but not on them and not on anyone else around them.
