### ISSUE TITLE
how do you log things?

### ISSUE THREAD

**Issue by alexvermaning0** [zfbx/zdiscord#76]
Before submitting your question have you checked the check the [FAQ](https://github.com/zfbx/zdiscord/wiki) or checked for similar issues already?: yes

**Question:**
i am trying to figure out how to add logs from other scripts or default qb ones. i can't seem to be able to figure it out from the wiki and FAQ

Information:
FiveM artifact #: does not really affect the question
Using QBCore?: yes
When did you last update QBCore if you are using it?: 1-2 months ago.

**Comment by zfbx** [comment]
The logs are done through an export, there's examples here https://zfbx.github.io/zdiscord/exports#log let me know if that helps you out

**Comment by alexvermaning0** [comment]
yes it does help me out. it will take some time to make it work how i want it. while i was making this question shortly after that i found a script that does what i want it. but im still using zdiscord too just for the QB commands.

these are all the things i wanted to log but there are also some of them that are not from qb-framework
anyways ill try to make it work with those exports

![image](https://user-images.githubusercontent.com/17603899/187255507-224a4d47-752e-4fb8-80d6-7fb67b03d10a.png)
