### ISSUE TITLE
Error using Screenshot

### ISSUE THREAD

**Issue by Sulb0** [zfbx/zdiscord#79]
I keep getting this error pop up in console when trying to screenshot an ID. Not sure how to fix, been trying to figure it out for a while now
![image](https://user-images.githubusercontent.com/99930543/189227481-6d2423ff-1ac1-40c2-b591-3c5ccab44037.png)
![image](https://user-images.githubusercontent.com/99930543/189227558-f08c3da2-4da4-4c7c-a052-4b1ba1f24261.png)

**Comment by zfbx** [comment]
What screenshot basic are you using? the official or a modified version to support like a different phone or something? you're missing a lot of details to this report that are in the template.. like fivem version and shit.. stuff that would be very helpful in saving me time needing to ask for them

**Comment by bruinp8n** [comment]
I have same issue, I had to switch to this fork https://github.com/project-error/screenshot-basic, as the new NPWD phone qbcore apps came out and alot of people in qbcore community are using it...  I didnt think anything was changed much to do with that call, but maybe you could see if zdiscord can support this fork aswell... I depend on the screenshot functionality for moderating, but desperately needed a new phone.. so im torn atm!

But, same error, asuming op may be using that fork aswell.

**Comment by zfbx** [comment]
![image](https://user-images.githubusercontent.com/1414927/189509993-316dcc08-5ad9-44a1-bc65-7f7c62aad521.png)
Seems they're moving away from that

**Comment by bruinp8n** [comment]
Alright, even better... ill switch back to the old screenshot basic n update npwd...

Im asuming the original poster was having the same issue so this should solve it unless im mistaken!  

Thanks for the quick response btw

**Comment by zfbx** [comment]
@bruinp8n no problem and yeah I assume so, since they haven't replied I will close the ticket :)
