### ISSUE TITLE
[BUG] Vehicle not storing correctly

### ISSUE THREAD

**Issue by JohnSacadorian1** [zfbx/zdiscord#82]
**Describe the bug**

**To Reproduce**
1. add a vehicle via zdiscord
2. go to garage, and pull it out
3. you are given "model does not exist in game".
4. whats happening is, it's not putting any data in the mods table in the database. therefore not letting you pull it out of the garage.

**Expected behavior**
able to give someone a vehicle using zdiscord and them being able to pull it out of the garage

**Screenshots**
none needed, unless requested.

**Information:**
 - FiveM Artifact #: current as of 10/10/22
 - Running QBCore?: yes
 - If running QBCore when did you last update it? on 10/01/22
 - Have you checked for other issues reporting this bug?: no

**Additional context**
none

**Comment by zfbx** [comment]
Is the vehicle you're trying to store a custom? honestly this functionality is almost impossible for zdiscord to handle and really should be an export from the garage or core to correctly add vehicles. I can't really do that in any good way that is supported by whatever garage someone is using which is really annoying.. wish someone would PR exports to add and remove vehicles to someone's garage so they are always stored properly.
